
const namesBones = [
    "Face Temporal",
    "Fossa Mandibular",
    "Poro Acústico Externo",
    "Tubérculo Articular",
    "Proc. Mastóide",
    "Fissura Timpanomastóidea",
    "Canal Carótico",
    "Forame Estilomastóideo",
    "Sulcos Arteriais",
    "Fissura Petrotimpânica",
    "Proc. Estilóide",
    "Meato Acústico Externo",
    "Fossa Pterigóidea",
    "Forame Mastóideo",
    "Lâmina Medial",
    "Sela Turca",
    "Forame Oval",
    "Proc. Zigomático",
    "Sulco do Seio Sigmóide",
    "Fossa Jugular",
    "Corpo",
    "Hâmulo Pterigóideo",
    "Fissura Orbital Superior",
    "Crista Esfenoidal",
    "Abertura do Seio Esfenoidal",
    "Asa Menor",
    "Asa Maior",
    "Forame Redondo",
    "Lâmina Lateral",
    "Forame Espinhoso",
    "Canal Pterigóideo",
    "Canal óptico",
    "Jugo esfenoidal",
    "Proc. clinóide anteerior",
    "Proc. clinóide posterior",
    "Fossa hipofisial",
    "Osso frontal",
    "Osso nasal",
    "Lamina orbit. osso etmoide",
    "Sutura coronal",
    "Osso pariental",
    "Proce. frontal do osso zigo.",
    "Asa maior do osso esfeno.",
    "Superf. orbit. do osso zigo.",
    "Superf. orbital da maxila",
    "Proce. zigo. da maxila",
    "Forame infraorbital",
    "Forame mentual",
    "Corpo da mandibula",
    "Proce. alveolar da maxila",
    "Espinha nasal int. da maxila",
    "Ramo da mandíbula",
    "Osso etmoide",
    "Osso zigomático",
    "Proce. temporal osso zigo.",
    "Osso esfenoide",
    "Processo frontal da maxila",
    "Osso temporal",
    "Forame supraorbital",
    "Glabe la do osso frontal,"
];



export default namesBones