
const namesBones = [
    "Face Temporal",
    "Fossa Mandibular",
    "Poro Acústico Externo",
    "Tubérculo Articular",
    "Proc. Mastóide",
    "Fissura Timpanomastóidea",
    "Canal Carótico",
    "Forame Estilomastóideo",
    "Sulcos Arteriais",
    "Fissura Petrotimpânica",
    "Proc. Estilóide",
    "Meato Acústico Externo",
    "Fossa Pterigóidea",
    "Forame Mastóideo",
    "Lâmina Medial",
    "Sela Turca",
    "Forame Oval",
    "Proc. Zigomático",
    "Sulco do Seio Sigmóide",
    "Fossa Jugular",
    "Corpo",
    "Hâmulo Pterigóideo",
    "Fissura Orbital Superior",
    "Crista Esfenoidal",
    "Abert. Seio Esfenoidal",
    "Asa Menor",
    "Asa Maior",
    "Forame Redondo",
    "Lâmina Lateral",
    "Forame Espinhoso",
    "Canal Pterigóideo",
    "Canal Ôptico",
    "Jugo Esfenoidal",
    "Proc. Clinóide Anterior",
    "Proc. Clinóide Posterior",
    "Fossa Hipofisial",
    "Osso Frontal",
    "Osso Nasal",
    "Lamina Orbit. O. Etmoide",
    "Sutura Coronal",
    "Osso Pariental",
    "Proce. Frontal Osso Zigo",
    "Asa Maior do Osso Esfeno",
    "Superf. Orbit. Osso Zigo",
    "Superf. Orbital da Maxila",
    "Proce. Zigo. da Maxila",
    "Forame Infraorbital",
    "Forame Mentual",
    "Corpo da Mandibula",
    "Proce. Alveolar da Maxila",
    "Espinha Nasal Ante. Maxila",
    "Ramo da Mandíbula",
    "Osso Etmoide",
    "Osso Zigomático",
    "Proce. Temporal Osso Zigo.",
    "Osso Esfenoide",
    "Processo Frontal da Maxila",
    "Osso Temporal",
    "Forame Supraorbital",
    "Glabela Osso Frontal",
    "Linha Temporal Superior",
    "Sutura Escamosa",
    "Meato Acúst. Ext. O. Temp.",
    "Part Petrosa Osso Temp.",
    "Osso Occipital",
    "Proce. Mastoide O. Temp.",
    "Proce. Estiloide O. Temp.",
    "Arco Zigomático",
    "Proce. Zigo. Osso Temp.",
    "Part Escamosa Osso Temp.",
    "Fossa Temporal",
    "Sutura Esfenopariental",
    "Linha Temporal Inferior",
    "Sutura Sagital",
    "Sutura Lambdóide",
    "Forame Parietal",
    "Osso Parietal",
    "Forame Incisivo",
    "Sutura Palatina Mediana",
    "Maxila",
    "Forame Palatino Maior",
    "Osso Zigomático",
    "Osso Palatino",
    "Arco Zigomático",
    "Coana",
    "Forame Oval",
    "Osso Temporal",
    "Canal Carotideo",
    "Forame Jugular",
    "Entalhe Mastoideo",
    "Linha Nucal Inferior",
    "Osso Occipital",
    "Protube. Occipital Ext.",
    "Linha Nucal Superior",
    "Crista Occipital Ext.",
    "Osso Parietal",
    "Forame Magno",
    "Canal Condilar",
    "Processo Mastóide",
    "Forame Estilomastóideo",
    "Fissura Petrotimpânica",
    "Forame Espinhoso",
    "Forame Lacerado",
    "Osso Esfenóide",
    "Vômer",
    "Hâmulo Pterigoide",
    "Fissura Orbitária Inf.",
    "Forame Palatino Menor",
    "Sutura Palatina Transver.",
    "Processo Palatino Maxila"
];



export default namesBones