import generateQuestions from '@/app/utils/helper/generateQuestions';
import namesBones from '@/app/utils/constants/namesBones';

export const correctAnswers: string[] = [
    "Forame Incisivo",
    "Sutura Palatina Mediana",
    "Maxila",
    "Forame Palatino Maior",
    "Osso Zigomático",
    "Osso Palatino",
    "Arco Zigomático",
    "Coana",
    "Forame Oval",
    "Osso Temporal",
    "Canal Carotideo",
    "Forame Jugular",
    "Entalhe Mastoideo",
    "Linha Nucal Inferior",
    "Osso Occipital",
    "Protube. Occipital Ext.",
    "Linha Nucal Superior",
    "Crista Occipital Ext.", 
    "Osso Parietal",
    "Forame Magno",
    "Canal Condilar",
    "Processo Mastóide",
    "Forame Estilomastóideo",
    "Fissura Petrotimpânica",
    "Forame Espinhoso",
    "Forame Lacerado",
    "Osso Esfenóide",
    "Vômer",
    "Hâmulo Pterigoide",
    "Fissura Orbitária Inf.",
    "Forame Palatino Menor",
    "Sutura Palatina Transver.",
    "Processo Palatino Maxila",
];

export const structure = correctAnswers.map((correctAnswer: string) => generateQuestions(namesBones, correctAnswer));